PyLadiesGhana/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    path('pyladiesorganizers/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('coc/', include('coc.urls', namespace='coc')),
    path('events/', include('events.urls', namespace='events')),
    path('about/', include('about.urls', namespace='about')),
    path('resources/', include('resources.urls', namespace='resources')),
    path('sponsors/', include('sponsors.urls', namespace='sponsors')),
    path('locations/', include('locations.urls', namespace='locations')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('blog/', include("pinax.blog.urls", namespace="pinax_blog")),
    path('announcements/', include("pinax.announcements.urls", namespace="pinax_announcements")),
    path('photologue/', include('photologue.urls', namespace='photologue')),
    path('', include('pwa.urls')),
]   

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Admin Header Settings
admin.site.site_header = "PyLadies Ghana Admin"
admin.site.index_title = "PyLadies Ghana"
admin.site.site_title = "PyLadies Ghana Webiste"

coc/urls.py
from django.urls import path
from . import views

app_name = 'coc'

urlpatterns = [
    path('', views.coc, name='coc'),
]

sponsors/urls.py
from django.urls import path
from . import views

app_name = 'sponsors'

urlpatterns = [
    path('', views.sponsors, name='sponsors'),
    path('support_us/', views.support_us,name='support_us'),
    path('prospectus/', views.sponsors, name='Prospectus'),
]

sponsors/models.py
from django.db import models


class Sponsor(models.Model):
    SPONSOR_PACKAGES = (('Bronze', 'Bronze - $500'),
                        ('Silver', 'Silver - $1000'),
                        ('Gold', 'Gold - $2500'),
                        ('Diamond', 'Diamond - $3500'),
                        ('Special', 'Special'),
                        ('Other', 'Other'),
                        )

    SPONSOR_TYPE =(('C', 'Corporate Sponsor'),
                   ('S', 'Special Sponsor'),
                   ('I', 'Individual Sponsor'),)

    name = models.CharField("sponsor name", max_length=200)
    category = models.CharField(max_length=15, choices=SPONSOR_PACKAGES)
    logo = models.ImageField(upload_to="sponsors/",max_length=255, blank=True, null=True)
    type = models.CharField("sponsor type", max_length=1, choices=SPONSOR_TYPE)
    url = models.URLField(default='', help_text='Link to Sponsor website', blank=True,)
    description = models.TextField(default='', help_text = "Description of the Sponsor", blank=True, null=True
                             )

    class Meta:
        managed = True

    def __str__(self):
        return self.name

sponsors/views.py
from __future__ import absolute_import
from django.shortcuts import render, reverse
from .models import Sponsor
from django.http import HttpRequest, HttpResponseRedirect

# Create your views here.


def Prospectus(request):
    context = {}
    template = 'prospectus.html'
    return render(request, template, context)



def sponsors(request):
    assert isinstance(request, HttpRequest)
    diamond = Sponsor.objects.filter(category="Diamond")
    gold = Sponsor.objects.filter(category="Gold")
    silver = Sponsor.objects.filter(category="Silver")
    bronze = Sponsor.objects.filter(category="Bronze")
    special = Sponsor.objects.filter(category="Special")
    individuals = Sponsor.objects.filter(type="I")

    return render(
        request,
        'sponsors/sponsors.html',
        {

            'diamond': diamond,
            'gold': gold,
            'silver': silver,
            'bronze': bronze,
            'special': special,
            'individuals': individuals,
        }
    )

def support_us(request):
    context = {}
    template = 'support_us.html'
    return render(request, template, context)

sponsors/templates/sponsors/sponsors.html
{% extends "base.html" %}
{% load i18n static %}
{% block title %} Sponsors {% endblock %}

{% block content %}
<header id="top" class="sub-header">
        <div class="container">
        </div>
        <!-- end .container -->
    </header><br><br>
    <!-- end .sub-header -->

<div class="container">
<section>
    <div class="col-md-12">
        <div class="panel panel-danger wow fadeInLeft">
                <div class="container">
                    <div class="row ">
                        <br >
                       <center><h3 class="page-title wow fadeInDown">Our Sponsors<br><small>Sponsors and Supporters of Python Ghana Ladies</small></h3><br> 
                        <div class="col-md-12">
                            <p>
                              <b>Python Ghana Ladies is generously sponsored by organisations that support its aim</b>
                            </p>
                            <p>Would you like to join them? <a href="{% url 'sponsors:support_us'%}"><b>See How to sponsor Python Ghana Ladies.</b></a></p></center><br><br>

                     {% if diamond %}

                    <h3 style="color: #000; text-shadow: 2px 2px 3px #b9f2ff"><b>Diamond Sponsors</b></h3>
                    <br><br>
                     <div class="container-fluid">
                       {% for sponsor in diamond %}
                            <div class="col-md-6">
                                <p><a href="{{ sponsor.url }}" target="blank"><img src="{{ sponsor.logo.url }}" class='img-responsive'></a></p>
                                <p><br>
                                {{ sponsor.description }}
                            </p>
                            </div>
                        {% endfor %}
                          </div><br><br>
                    {% endif %}


                     {% if gold %}
                    <h4 style="color: #000; text-shadow: 2px 2px 3px #FFD700"><b>Gold Sponsors</b></h4>
                    <br />
                    <div class="container">
                    {% for sponsor in gold %}
                        <div class="col-md-6">
                            <a href="{{ sponsor.url }}" target="_blank"><img src="{{ sponsor.logo.url }}" class='img-responsive'></a>
                            <p><br>
                                {{ sponsor.description }}
                            </p>
                        </div>
                        {% endfor %}
                        </div>
                        <br><br>
                    {% endif %}



                     {% if silver %}
                    <h5 style="color: #000; text-shadow: 2px 2px 3px #C0C0C0"><b>Silver Sponsors<b></h5>
                    <br />
                    <div class="container">
                    {% for sponsor in silver %}
                        <div class="col-md-6">
                            <a href="{{ sponsor.url }}" target="_blank"><img src="{{ sponsor.logo.url }}" class='img-responsive'></a>
                            <p><br>
                                {{ sponsor.description }}
                            </p>
                        </div>
                        {% endfor %}
                        </div>
                        <br><br>
                    {% endif %}



                         {% if bronze %}
                    <h6 style="color: #000; text-shadow: 2px 2px 3px #cd7f32"><b>Bronze Sponsors</b></h6>
                    <br />
                    <div class="container">
                    {% for sponsor in bronze %}
                        <div class="col-md-6">
                            <a href="{{ sponsor.url }}" target="_blank"><img src="{{ sponsor.logo.url }}" class='img-responsive'></a>
                            <p><br>
                                {{ sponsor.description }}
                            </p>
                        </div>
                        {% endfor %}
                        </div><br><br>
                    {% endif %}

                       {% if special %}
                    <h6 style="color: #000; text-shadow: 2px 2px 3px #cd7012"><b>Special Sponsors</b></h6>
                    <br />
                    <div class="container">
                    {% for sponsor in special %}
                        <div class="col-md-4">
                            <a href="{{ sponsor.url }}" target="_blank"><img src="{{ sponsor.logo.url }}" class='img-responsive'></a>
                            <p>
                                {{ sponsor.description }}
                            </p><br>
                        </div>
                        {% endfor %}
                        </div><br><br>
                    {% endif %}

                     <!--<hr style="background-color: #fff;border-top: 2px dashed #8c8b8b;width: 1000px;height: 0px;">--> 

                            {% if individuals %}
                    <h6 style="color: #000; text-shadow: 2px 2px 3px "><b>Individual Sponsors</b></h6>
                    <div class="container-fluid">
                        <div class="row">
                                {% for individual in individuals %}
                                <div class="col-md-2">
                                    <h6><a href="{{ individual.url }}" target="_blank">{{ individual.name }}</a></h6>
                                </div>
                                {% endfor %}

                        </div>
                    </div>
                    {% endif %}
                    <br><br>

                    </div>

                        </div>
                    </div>
                </div>
            </div>
    
</section>
</div>
<br ><br >
{% endblock %}

sponsors/templates/sponsors/sponsors_form.html
{% extends "base.html" %}
{% load crispy_forms_tags i18n static %}
{% block title %} Sponsorship Form {% endblock %}


{% block content %}

    <header id="top" class="sub-header">
        <div class="container">
        </div>
        <!-- end .container -->
    </header><br><br>


<section>
    <div class="col-md-12">
        <div class="panel panel-danger wow fadeInLeft">
                <div class="container"> 
                    <div class="row ">
                        <h5 class="page-title wow fadeInDown">Apply for Sponsorship<br><small>Help Sponsor Python Ghana Ladies</small></h5><br>
            
                                                <div class="container"> 
                                                    <div class="nav-center bottom-space-lg">
                                                 </div>
                                                                    <form class="form col-md-8" action="" method="post">
                                                                            {% crispy form form.helper %}
                                                                                {% csrf_token %}
                                                                    </form>
                                                </div>
                    </div>
                </div>
            </div>
    </div>
</section>

{% endblock %}