PyLadiesGhana/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    path('pyladiesorganizers/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('coc/', include('coc.urls', namespace='coc')),
    path('events/', include('events.urls', namespace='events')),
    path('about/', include('about.urls', namespace='about')),
    path('resources/', include('resources.urls', namespace='resources')),
    path('sponsors/', include('sponsors.urls', namespace='sponsors')),
    path('locations/', include('locations.urls', namespace='locations')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('blog/', include("pinax.blog.urls", namespace="pinax_blog")),
    path('announcements/', include("pinax.announcements.urls", namespace="pinax_announcements")),
    path('photologue/', include('photologue.urls', namespace='photologue')),
    path('', include('pwa.urls')),
]   

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Admin Header Settings
admin.site.site_header = "PyLadies Ghana Admin"
admin.site.index_title = "PyLadies Ghana"
admin.site.site_title = "PyLadies Ghana Webiste"

coc/urls.py
from django.urls import path
from . import views

app_name = 'coc'

urlpatterns = [
    path('', views.coc, name='coc'),
]

sponsors/urls.py
from django.urls import path
from . import views

app_name = 'sponsors'

urlpatterns = [
    path('', views.sponsors, name='sponsors'),
    path('support_us/', views.support_us,name='support_us'),
    path('prospectus/', views.sponsors, name='Prospectus'),
]

sponsors/models.py
from django.db import models


class Sponsor(models.Model):
    SPONSOR_PACKAGES = (('Bronze', 'Bronze - $500'),
                        ('Silver', 'Silver - $1000'),
                        ('Gold', 'Gold - $2500'),
                        ('Diamond', 'Diamond - $3500'),
                        ('Special', 'Special'),
                        ('Other', 'Other'),
                        )

    SPONSOR_TYPE =(('C', 'Corporate Sponsor'),
                   ('S', 'Special Sponsor'),
                   ('I', 'Individual Sponsor'),)

    name = models.CharField("sponsor name", max_length=200)
    category = models.CharField(max_length=15, choices=SPONSOR_PACKAGES)
    logo = models.ImageField(upload_to="sponsors/",max_length=255, blank=True, null=True)
    type = models.CharField("sponsor type", max_length=1, choices=SPONSOR_TYPE)
    url = models.URLField(default='', help_text='Link to Sponsor website', blank=True,)
    description = models.TextField(default='', help_text = "Description of the Sponsor", blank=True, null=True
                             )

    class Meta:
        managed = True

    def __str__(self):
        return self.name

sponsors/views.py
from __future__ import absolute_import
from django.shortcuts import render, reverse
from .models import Sponsor
from django.http import HttpRequest, HttpResponseRedirect

# Create your views here.


def Prospectus(request):
    context = {}
    template = 'prospectus.html'
    return render(request, template, context)



def sponsors(request):
    assert isinstance(request, HttpRequest)
    diamond = Sponsor.objects.filter(category="Diamond")
    gold = Sponsor.objects.filter(category="Gold")
    silver = Sponsor.objects.filter(category="Silver")
    bronze = Sponsor.objects.filter(category="Bronze")
    special = Sponsor.objects.filter(category="Special")
    individuals = Sponsor.objects.filter(type="I")

    return render(
        request,
        'sponsors/sponsors.html',
        {

            'diamond': diamond,
            'gold': gold,
            'silver': silver,
            'bronze': bronze,
            'special': special,
            'individuals': individuals,
        }
    )

def support_us(request):
    context = {}
    template = 'support_us.html'
    return render(request, template, context)

sponsors/templates/prospectus.html
{% extends "base.html" %}

{% block header %}Our Prospectus{% endblock %}
{% block content %}


<div class="container">

                        <h3>Our Prospectus</h3>

</div>





{% endblock %}

sponsors/templates/support_us.html
{% extends "base.html" %}
{% load i18n static %}
{% block title %} Support Us {% endblock%}


{% block content %}

<header id="top" class="sub-header">
        <div class="container">
        </div>
        <!-- end .container -->
    </header>
    
      <section>
      	<div class="container">
      	 <div class="col-sm-12">
                     <div class="section-title wow fadeInUp">
                        <h4>  </h4>
                     </div>
                    <div class="panel panel-danger wow fadeInLeft">
                          <div class="row">
							      
							      	<div class="container">
							          <center>  <br ><h3>Support Us<br ><small>Become A Sponsor</small></h3><br >
							            <h4>Why we need sponsors</h6>
							            <p>Python Ghana Ladies is wholly organized by volunteers. We therefore need sponsors to help us cover the costs of:
							            <ul class="list-group" id="sponsor-container">
							                <li class="list-group-item list-group-item-info">basic running expenses;</li>
							                <li class="list-group-item list-group-item-info">provide a decent location to host Meetups;</li>
							                <li class="list-group-item list-group-item-info">reimburse the travel and accommodation costs of our speakers;</li>
											<li class="list-group-item list-group-item-success">provide financial assistance to participant who cannot otherwise afford to attend the Meetups;</li>
							                <li class="list-group-item list-group-item-success">catering and refreshments;</li>
							                <li class="list-group-item list-group-item-success">educational materials for the tutorials;</li>
							                <li class="list-group-item list-group-item-success">video recording of talks!</li>
							            </ul></center> 
							              <br><br>

							       <!--       <h6>Sponsor Packages</h6>
							              <table>
							                  <tr>
							                      <td><h5 style="color: #000; text-shadow: 2px 2px 3px #cd7f32">Bronze <span><span>($500)</span></span></h5></td>
							                      <td><h5 style="color: #000; text-shadow: 2px 2px 3px #C0C0C0">Silver <span><span>($1000)</span></span></h5></td>
							                  </tr>
							                  <tr>
							                    <td>
									                   <center> <p>Includes:</p>
														<ul>
															<li>a thank-you in the programme booklet</li><span></span>
															<li>your exhibition materials at the venue</li><span></span>
															<li>your logo, and a link on our website</li><span></span>
															<li>mentions in press releases conference  </li><span></span>
															<li>news items, email and Twitter messages</li><span></span> 
															<li>to the community</li>
														</ul></center>
									          	</td>

							                    <td>
														<center><p>Similar to Bronze, plus:</p>

														<ul><li>All of the above</li>
															<li><strong>2 tickets</strong> to the conference</li>
															<li>a stand at the venue</li>
															<li>a quarter-page advertisement in the programme</li>
															<li>more prominent mentions</li>
														</ul></center>
							                    </td>
							                  </tr>
							              </table>
							              <table>
							                  <tr>
							                      <td><h5 style="color: #000; text-shadow: 2px 2px 3px #FFD700">  Gold <span>($2500)</span></h5></td>
							                      <td><h5 style="color: #000; text-shadow: 2px 2px 3px #b9f2ff"><b>Diamond </b><span>($3500)</span></h5></td>
							                  </tr>
							                  <tr>
							                    <td>
							                    	<p>Similar to Silver, plus:</p>
													<ul>
														<li>All of the above</li>
														<li>Send Recruiting emails to attendees on your behalf</li>
														<li><strong>4 tickets</strong> to the conference</li>
														<li>a half-page advertisement in the conference programme</li>
														<li>even more prominent mentions</li>
													</ul>
							                    </td>
							                    <td>
							                    	<p>Similar to Gold, plus:</p>
													<ul>
														<li>All of the above</li>
														<li><strong>6 tickets</strong> to the conference</li>
														<li>a full-page advertisement in the conference programme</li>
														<li>very prominent mentions</li>
														<li>Recruitment stand in exhibition hall</li>
														<li>Company's Brochures in welcome kit (Provided by the company) </li>
														<li>Opportunity to address the conference</li>
													</ul>
							                    </td>
							                  </tr>
							              </table>
							              <br >
							             <center><h6><b>Special Sponsorship</b></h6></center> 
											<p> Our special sponsorship package is designed for organisations and individuals looking to make a contribution to building a stronger Python community in Ghana through PyCon Ghana. If you would like to Sponsor other aspects of the conference such as Catering, Media, Internet or any form of sponsorship both in cash or in kind, please reach out to us for more Information.
											</p>
											</br>
											<center><p> <a href="{% static 'files/Prospectus.pdf' %}" download="Python Ghana Ladies Prospectus.pdf"><button style="font-size:16px"><b>Download our Prospectus HERE</b><i class="fa fa-download"></i></button></a> <br><br></center> -->


											<center><p><b>If you are interested and wish to sponsor PyLadies Ghana, then please contact us via
							                  <a href="mailto:ghana@pyladies.com">ghana@pyladies.com</a>.</b><br> You can see our current Sponsors <a href="{% url 'sponsors:sponsors' %}">Here</a></p></center>

							          </div>
							      </div>
							      
							</div>
			      </div>
</div>
    </section>
</p>

{% endblock %}